#!/usr/bin/env bash
# install nginx in my web server and output a message
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx status
sudo curl 34.207.251.253
sudo echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
sudo curl 34.207.251.253
curl -sI 34.198.248.145/

