#!/usr/bin/env bash
# install nginx in my web server and output a message
sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart

