#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt -y install haproxy
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT

frontend http_web\n\tbind *:80\n\tdefault_backend rgw
backend rgw\n\tbalance roundrobin
    server  4418-web-01 34.224.57.138
    server  4418-web-02 54.209.132.114
EOT
sudo service haproxy restart
