#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt -y install haproxy
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT

frontend http_web
    bind *:80
    default_backend 4418-web
backend 4418-web
    balance roundrobin
    server  4418-web-01 34.224.57.138
    tserver 4418-web-02 54.209.132.114
EOT
sudo service haproxy restart
