#!/usr/bin/env bash
#debug the nginx configuration to curl port 80
sudo rm -r /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
