#!/usr/bin/env bash
#this file print Best School 10 times
x=0
while [ $x -le 9 ]
do
    x=$(( x + 1 ))
    if [ $x = 4 ]
    then
        echo "bad luck"
    elif [ $x = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
done
