#!/usr/bin/env bash
#this script print from 1 till 20 replacing some numberss with text
x=0
while [ $x -le 19 ]
do
x=$(( x + 1 ))
echo "$x"
case $x in
    5) echo "bad luck from China";;
    10) echo "bad luck from Japan";;
    17) echo "bad luck from Italy";;
    esac
done
