#!/usr/bin/env bash
#nginx must be running as nginx user
sudo pkill nginx
sudo pkill apache2
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 700 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo service nginx start
