#!/usr/bin/env bash
#nginx must be running as nginx user
pkill nginx
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo service nginx start
